name: Feature Request
description: Suggest a new feature or enhancement for Onlook
title: "[Feature Request]: "
labels: ["enhancement"]
assignees:
  - onlook-dev
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature for Onlook!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like Onlook to [...]
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I've tried to solve this by [...]
    validations:
      required: false
  - type: dropdown
    id: feature_area
    attributes:
      label: Feature Area
      description: What area of Onlook does this feature relate to?
      multiple: true
      options:
        - Browser
        - Editor
        - Write-to-code
        - AI chat
        - Variables
        - Components
        - Hosting
        - Other
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
      default: 0
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or mockups about the feature request here.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this feature request, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
